version: '3'

services:
  dnsmasq:
    container_name: dnsmasq
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    network_mode: "host"
    volumes:
      - /etc/dnsmasq.d/local_records.conf:/etc/dnsmasq.d/local_records.conf
      - /etc/dnsmasq.d/forwarding.conf:/etc/dnsmasq.d/forwarding.conf
    cap_add:
      - NET_ADMIN
    command: ["dnsmasq", "-k", "--log-facility=-"]
    restart: always
