version: '3'

services:
  unbound:
    container_name: unbound
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    network_mode: "host"
    volumes:
      - /etc/unbound/unbound.log:/etc/unbound/unbound.log
      - /etc/unbound/unbound.conf:/etc/unbound/unbound.conf
    cap_add:
      - NET_ADMIN
    command: ["unbound", "-d"]
    restart: always
