#cloud-config

package_update: true
package_upgrade: true
%{ if length(packages) > 0 ~}
packages:
%{ for package in packages ~}
  - ${package}
%{ endfor ~}
%{ endif ~}

%{~ if length(users) > 0 }
users:
%{ for user in users ~}
  - name: ${user.username}
    uid: ${user.uid}
%{ endfor ~}
%{ endif ~}

%{~ if length(files) > 0 }
write_files:
%{ for path, data in files ~}
  - path: ${path}
    owner: ${lookup(data, "owner", "root")}
    permissions: ${lookup(data, "permissions", "0644")}
    content: |
      ${indent(6, data.content)}
%{ endfor ~}
%{ endif ~}

%{~ if length(boot_commands) > 0 }
bootcmd:
%{ for command in boot_commands ~}
  - ${command}
%{ endfor ~}
%{ endif ~}

%{~ if length(run_commands) > 0 }
runcmd:
%{ for command in run_commands ~}
  - ${command}
%{ endfor ~}
%{ endif ~}
