version: '3'
services:
  app6-nginx-8081:
    container_name: app6-nginx-8081
    build:
      context: ./nginx/nginx-8081
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - /etc/ssl/app/cert.pem:/etc/ssl/app/cert.pem
      - /etc/ssl/app/key.pem:/etc/ssl/app/key.pem
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
  app6-9001:
    container_name: app6-9001
    build:
      context: ./app/app
      dockerfile: Dockerfile
    network_mode: host
    command: uvicorn main:app --host '0.0.0.0' --port 9001
    restart: always
