version: '3'
services:
  app5-nginx-8080:
    container_name: app5-nginx-8080
    build:
      context: ./nginx/nginx-8080
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - /etc/ssl/app/cert.pem:/etc/ssl/app/cert.pem
      - /etc/ssl/app/key.pem:/etc/ssl/app/key.pem
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
  app5-9000:
    container_name: app5-9000
    build:
      context: ./app/app
      dockerfile: Dockerfile
    network_mode: host
    command: uvicorn main:app --host '0.0.0.0' --port 9000
    restart: always
