version: '3'
services:
  app1-80:
    container_name: app1-80
    build:
      context: ./app/app
      dockerfile: Dockerfile
    network_mode: host
    command: uvicorn main:app --host '0.0.0.0' --port 80
    restart: always
  app1-ipv6-80:
    container_name: app1-ipv6-80
    build:
      context: ./app/app
      dockerfile: Dockerfile
    network_mode: host
    command: uvicorn main:app --host '::' --port 80
    restart: always
