version: '3'
services:
  app3-8081:
    container_name: app3-8081
    build:
      context: ./app/app
      dockerfile: Dockerfile
    network_mode: host
    command: uvicorn main:app --host '0.0.0.0' --port 8081
    restart: always
