version: '3'
services:
  %{~ if try(NGINX.enable_tls, false) ~}
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ${NGINX.cert_path}:${NGINX.cert_path}
      - ${NGINX.key_path}:${NGINX.key_path}
      - ${NGINX.config_path}:${NGINX.config_path}
  %{~ endif ~}
  %{~ for v in APPS }
  ${v.name}:
    container_name: ${v.name}
    build:
      context: ./${v.name}
      dockerfile: Dockerfile
    network_mode: host
  %{~ endfor ~}
